#!/bin/bash
#################################################
# 
# Inject into kernel text segment
# Author: HIT CS HDMC team.
# Create: 2010-6-17 10:17:54
# Last modified: 2010-6-17 10:17:55
# 
#################################################
echo $1 > /proc/memoryEngine/kFuncName
echo 0 > /proc/memoryEngine/memVal
echo 6 > /proc/memoryEngine/ctl

